misc: board_id: Fix unused result error
Fixes:
drivers/misc/board_id.c:65:2: error: ignoring return value of function
declared with 'warn_unused_result' attribute [-Werror,-Wunused-result]
        devm_pinctrl_get_select_default(dev);
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ~~~
1 error generated.

Change-Id: I0b6489bbcaef06f39feaf79c78a0ee53d5f82f61